### ISSUE TITLE
Failed to activate the emmet-jsx-css-modules package-2

### ISSUE THREAD

**Issue by Edge00** [ambethia/emmet-jsx-css-modules#7] opened 2017-04-12 03:17 UTC
![1](https://cloud.githubusercontent.com/assets/23715779/24939669/931f64b0-1f71-11e7-994d-fcf5bf72e787.png)
This is win10
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at Object.activate (file:///C:/Users/admin/.atom/packages/emmet-jsx-css-modules/lib/emmet-jsx-css-modules.js:13:28)
    at Package.module.exports.Package.activateNow (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:218:19)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\atom-environment.js:812:28

**Comment by ambethia** [comment] 2017-04-15 02:51
Duplicate of #2

**Closed as completed by ambethia** 2017-04-15 02:51 UTC
